/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CommitService } from "../commit.service";
import { CommitCreateInput } from "./CommitCreateInput";
import { Commit } from "./Commit";
import { CommitFindManyArgs } from "./CommitFindManyArgs";
import { CommitWhereUniqueInput } from "./CommitWhereUniqueInput";
import { CommitUpdateInput } from "./CommitUpdateInput";
import { MetricFindManyArgs } from "../../metric/base/MetricFindManyArgs";
import { Metric } from "../../metric/base/Metric";
import { MetricWhereUniqueInput } from "../../metric/base/MetricWhereUniqueInput";

export class CommitControllerBase {
  constructor(protected readonly service: CommitService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Commit })
  async createCommit(@common.Body() data: CommitCreateInput): Promise<Commit> {
    return await this.service.createCommit({
      data: data,
      select: {
        choice: true,
        createdAt: true,
        developerCode: true,
        diff: true,
        generatedCode: true,
        id: true,
        message: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Commit] })
  @ApiNestedQuery(CommitFindManyArgs)
  async commits(@common.Req() request: Request): Promise<Commit[]> {
    const args = plainToClass(CommitFindManyArgs, request.query);
    return this.service.commits({
      ...args,
      select: {
        choice: true,
        createdAt: true,
        developerCode: true,
        diff: true,
        generatedCode: true,
        id: true,
        message: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Commit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async commit(
    @common.Param() params: CommitWhereUniqueInput
  ): Promise<Commit | null> {
    const result = await this.service.commit({
      where: params,
      select: {
        choice: true,
        createdAt: true,
        developerCode: true,
        diff: true,
        generatedCode: true,
        id: true,
        message: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Commit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCommit(
    @common.Param() params: CommitWhereUniqueInput,
    @common.Body() data: CommitUpdateInput
  ): Promise<Commit | null> {
    try {
      return await this.service.updateCommit({
        where: params,
        data: data,
        select: {
          choice: true,
          createdAt: true,
          developerCode: true,
          diff: true,
          generatedCode: true,
          id: true,
          message: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Commit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCommit(
    @common.Param() params: CommitWhereUniqueInput
  ): Promise<Commit | null> {
    try {
      return await this.service.deleteCommit({
        where: params,
        select: {
          choice: true,
          createdAt: true,
          developerCode: true,
          diff: true,
          generatedCode: true,
          id: true,
          message: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/metrics")
  @ApiNestedQuery(MetricFindManyArgs)
  async findMetrics(
    @common.Req() request: Request,
    @common.Param() params: CommitWhereUniqueInput
  ): Promise<Metric[]> {
    const query = plainToClass(MetricFindManyArgs, request.query);
    const results = await this.service.findMetrics(params.id, {
      ...query,
      select: {
        commit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/metrics")
  async connectMetrics(
    @common.Param() params: CommitWhereUniqueInput,
    @common.Body() body: MetricWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      metrics: {
        connect: body,
      },
    };
    await this.service.updateCommit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/metrics")
  async updateMetrics(
    @common.Param() params: CommitWhereUniqueInput,
    @common.Body() body: MetricWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      metrics: {
        set: body,
      },
    };
    await this.service.updateCommit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/metrics")
  async disconnectMetrics(
    @common.Param() params: CommitWhereUniqueInput,
    @common.Body() body: MetricWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      metrics: {
        disconnect: body,
      },
    };
    await this.service.updateCommit({
      where: params,
      data,
      select: { id: true },
    });
  }
}
